CREATE TABLE `clothes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `clothe_name` varchar(255) NOT NULL,
  `clothe_image` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `clothes` (`id`, `clothe_name`) VALUES
(1, 'women-skirt (3).jpg'),
(2, 'women-skirt.jpg'),
(3, 'women-skirt (2).jpg'),
(4, 'women-skirt (4).jpg'),
(5, 'women-hoodie (3).jpg'),
(6, 'women-hoodie (2).jpg'),
(7, 'women-hoodie.jpg'),
(8, 'women-hoodie (5).jpg'),
(9, 'women-hoodie (4).jpg'),
(10, 'women-baggy (2).jpg'),
(11, 'women-baggy.jpg'),
(12, 'women-baggy (3).jpg'),
(13, 'women-baggy (4).jpg'),
(14, 'women-shorts (4).jpg'),
(15, 'women-shorts (3).jpg'),
(16, 'women-shorts (2).jpg'), 
(17, 'women-shorts.jpg'),
(18, 'women-flare.jpg'),
(19, 'women-flare (2).jpg'),
(20, 'women-flare (3).jpg'),
(21, 'women-bootcut (5).jpg'),
(22, 'women-bootcut (4).jpg'),
(23, 'women-bracelet (6).jpg'),
(24, 'women-bracelet (4).jpg'),
(25, 'women-bracelet (7).jpg'),
(26, 'women-bracelet (8).jpg'),
(27, 'women-bracelet (5).jpg'),
(28, 'women-bracelet (9).jpg'),
(29, 'women-bracelet (3).JPG'),
(30, 'women-ring (3).jpg'),
(31, 'women-ring (7).jpg'),
(32, 'women-ring (2).jpg'),
(33, 'women-ring.jpg'),
(34, 'women-ring (6).jpg'),
(35, 'women-ring (5).jpg'),
(36, 'women-ring (4).jpg'),
(37, 'women-earring (5).jpg'),
(38, 'women-earring (2).jpg'),
(39, 'women-earring (3).jpg'),
(40, 'women-earring (4).jpg'),
(41, 'women-earring (7).jpg'),
(42, 'women-earring (6).jpg'),
(43, 'unisex-belt (4).jpg'),
(44, 'unisex-belt (3).jpg'),
(45, 'unisex-belt (5).jpg'),
(46, 'unisex-belt (7).jpg'),
(47, 'unisex-belt (6).jpg'),
(48, 'unisex-baggy (3).jpg'),
(49, 'unisex-baggy (2).jpg'),
(50, 'men-bracelet (7).jpg'),
(51, 'men-bracelet (3).jpg'),
(52, 'men-bracelet (2).jpg'),
(53, 'men-bracelet (4).jpg'),
(54, 'men-bracelet.jpg'),
(55, 'men-bracelet (6).jpg'),
(56, 'men-bracelet (5).jpg'),
(57, 'men-necklace (5).jpg'),
(58, 'men-necklace (4).jpg'),
(59, 'men-necklace.jpg'),
(60, 'men-necklace (3).jpg'),
(61, 'men-necklace (2).jpg'),
(62, 'men-necklace (6).jpg'),
(63, 'men-ring (9).jpg'),
(64, 'men-ring (8).jpg'),
(65, 'men-ring (5).jpg'),
(66, 'men-ring (6).jpg'),
(67, 'men-ring (4).jpg'),
(68, 'men-ring (3).jpg'),
(69, 'men-ring (7).jpg'),
(70, 'men-ring (2).jpg'),
(71, 'men-shirt (3).jpg'),
(72, 'men-buttonup (6).jpg'),
(73, 'men-buttonup (4).jpg'),
(74, 'men-buttonup (3).jpg'),
(75, 'men-buttonup (2).jpg'),
(76, 'men-buttonup (5).jpg'),
(77, 'men-baggy (2).jpg'),
(78, 'men-baggy.jpg'),
(79, 'men-baggy (3).jpg'),
(80, 'men-slim (6).jpg'),
(81, 'men-slim (5).jpg'),
(82, 'men-slim (4).jpg'),
(83, 'men-slim (3).jpg'),
(84, 'men-slim (2).jpg'),
(85, 'men-hoodie (2).jpg'),
(86, 'men-hoodie (3).jpg'),
(87, 'men-hoodie (5).jpg'),
(88, 'men-hoodie (7).jpg'),
(89, 'men-hoodie (8).jpg'),
(90, 'men-hoodie (4).jpg'),
(91, 'men-hoodie (6).jpg'),
(92, 'men-hoodie.JPG'),
(93, 'men-longsleeve (2).JPG'),
(94, 'men-longsleeve (3).JPG'),
(95, 'men-longsleeve (4).JPG'),
(96, 'men-longsleeve (5).JPG'),
(97, 'men-longsleeve (6).JPG'),
(98, 'men-longsleeve (7).JPG'),
(99, 'women-longsleeve (2).JPG'),
(100, 'women-longsleeve (3).JPG'); 

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_admin` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `users` (`id`, `username`, `email`, `password`, `is_admin`) VALUES
(1, 'drin', 'vllasidrin@gmail.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'true');

CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
